export const baseUrl =
  process.env.NODE_ENV === "development"
    ? "//153.92.221.4:8120/v1"
    : "//api.matcher.pl/v1";

export const hour = 3600;

export const hoursMarks = [
  {
    value: 0,
    label: "12pm",
  },
  {
    value: 1,
    label: "1am",
  },
  {
    value: 2,
    label: "2am",
  },
  {
    value: 3,
    label: "3am",
  },
  {
    value: 4,
    label: "4am",
  },
  {
    value: 5,
    label: "5am",
  },
  {
    value: 6,
    label: "6am",
  },
  {
    value: 7,
    label: "7am",
  },
  {
    value: 8,
    label: "8am",
  },
  {
    value: 9,
    label: "9am",
  },
  {
    value: 10,
    label: "10am",
  },
  {
    value: 11,
    label: "11am",
  },
  {
    value: 12,
    label: "12am",
  },
  {
    value: 13,
    label: "1pm",
  },
  {
    value: 14,
    label: "2pm",
  },
  {
    value: 15,
    label: "3pm",
  },
  {
    value: 16,
    label: "4am",
  },
  {
    value: 17,
    label: "5am",
  },
  {
    value: 18,
    label: "6pm",
  },
  {
    value: 19,
    label: "7pm",
  },
  {
    value: 20,
    label: "8pm",
  },
  {
    value: 21,
    label: "9am",
  },
  {
    value: 22,
    label: "10pm",
  },
  {
    value: 23,
    label: "11pm",
  },
  {
    value: 24,
    label: "12pm",
  },
  {
    value: 25,
    label: "1am",
  },
  {
    value: 26,
    label: "2am",
  },
  {
    value: 27,
    label: "3am",
  },
  {
    value: 28,
    label: "4am",
  },
  {
    value: 29,
    label: "5am",
  },
  {
    value: 30,
    label: "6am",
  },
  {
    value: 31,
    label: "7am",
  },
  {
    value: 32,
    label: "8am",
  },
  {
    value: 33,
    label: "9am",
  },
  {
    value: 34,
    label: "10am",
  },
  {
    value: 35,
    label: "11am",
  },
  {
    value: 36,
    label: "12am",
  },
  {
    value: 37,
    label: "1pm",
  },
  {
    value: 38,
    label: "2pm",
  },
  {
    value: 39,
    label: "3pm",
  },
  {
    value: 40,
    label: "4pm",
  },
  {
    value: 41,
    label: "5pm",
  },
  {
    value: 42,
    label: "6pm",
  },
  {
    value: 43,
    label: "7pm",
  },
  {
    value: 44,
    label: "8pm",
  },
  {
    value: 45,
    label: "9pm",
  },
  {
    value: 46,
    label: "10pm",
  },
  {
    value: 47,
    label: "11pm",
  },
  {
    value: 48,
    label: "12pm",
  },
];

export const days = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];
export const sampleCourts = [
  {
    id: 27,
    name: "Pratt Clay",
    address: {
      country: "Uruguay",
      city: "Nicholson",
      street_name: "Havens Place",
      postal_code: "10-694",
      latitude: 50.4178,
      longitude: 16.946,
      street_number: "11/13",
    },
    details: {
      courts_number: 3,
      hoops_number: 2,
      lightning: false,
    },
    created: "2019-08-29T12:08:28 -02:00",
  },
  {
    id: 433,
    name: "Spencer Estes",
    address: {
      country: "Philippines",
      city: "Calvary",
      street_name: "Hart Street",
      postal_code: "35-550",
      latitude: 51.9196,
      longitude: 17.0185,
      street_number: "57/3",
    },
    details: {
      courts_number: 2,
      hoops_number: 7,
      lightning: false,
    },
    created: "2017-09-18T12:38:33 -02:00",
  },
  {
    id: 122,
    name: "Haney Roman",
    address: {
      country: "US Minor Outlying Islands",
      city: "Springdale",
      street_name: "Glendale Court",
      postal_code: "59-241",
      latitude: 50.0845,
      longitude: 16.5864,
      street_number: "56/15",
    },
    details: {
      courts_number: 2,
      hoops_number: 1,
      lightning: true,
    },
    created: "2019-03-17T12:22:26 -01:00",
  },
  {
    id: 785,
    name: "Booth Glover",
    address: {
      country: "Greece",
      city: "Cliffside",
      street_name: "Auburn Place",
      postal_code: "53-927",
      latitude: 50.0986,
      longitude: 17.2561,
      street_number: "34/6",
    },
    details: {
      courts_number: 3,
      hoops_number: 8,
      lightning: false,
    },
    created: "2014-12-19T07:50:37 -01:00",
  },
  {
    id: 451,
    name: "Chelsea Harrell",
    address: {
      country: "Micronesia",
      city: "Springville",
      street_name: "Arion Place",
      postal_code: "42-788",
      latitude: 50.0153,
      longitude: 17.3403,
      street_number: "26/5",
    },
    details: {
      courts_number: 4,
      hoops_number: 8,
      lightning: true,
    },
    created: "2019-07-01T07:43:14 -02:00",
  },
  {
    id: 64,
    name: "Richard Lester",
    address: {
      country: "Pitcairn",
      city: "Joppa",
      street_name: "Lafayette Walk",
      postal_code: "72-679",
      latitude: 51.1043,
      longitude: 16.3197,
      street_number: "27/16",
    },
    details: {
      courts_number: 2,
      hoops_number: 5,
      lightning: true,
    },
    created: "2020-11-17T07:42:25 -01:00",
  },
  {
    id: 539,
    name: "Cleveland Waters",
    address: {
      country: "Kazakhstan",
      city: "Harborton",
      street_name: "Kay Court",
      postal_code: "98-376",
      latitude: 50.9196,
      longitude: 16.868,
      street_number: "35/4",
    },
    details: {
      courts_number: 3,
      hoops_number: 6,
      lightning: true,
    },
    created: "2020-02-29T11:10:31 -01:00",
  },
  {
    id: 145,
    name: "Molly Cline",
    address: {
      country: "Seychelles",
      city: "Trona",
      street_name: "Nautilus Avenue",
      postal_code: "58-543",
      latitude: 50.4947,
      longitude: 17.9698,
      street_number: "41/4",
    },
    details: {
      courts_number: 4,
      hoops_number: 7,
      lightning: true,
    },
    created: "2021-02-09T08:10:00 -01:00",
  },
  {
    id: 825,
    name: "Hampton Edwards",
    address: {
      country: "Belgium",
      city: "Bourg",
      street_name: "Goodwin Place",
      postal_code: "78-989",
      latitude: 50.6377,
      longitude: 17.53,
      street_number: "23/19",
    },
    details: {
      courts_number: 4,
      hoops_number: 4,
      lightning: false,
    },
    created: "2019-01-07T02:59:28 -01:00",
  },
  {
    id: 335,
    name: "Olivia Williamson",
    address: {
      country: "Palau",
      city: "Beason",
      street_name: "Canal Avenue",
      postal_code: "89-430",
      latitude: 50.227,
      longitude: 16.6025,
      street_number: "39/3",
    },
    details: {
      courts_number: 3,
      hoops_number: 3,
      lightning: false,
    },
    created: "2015-08-16T08:48:32 -02:00",
  },
  {
    id: 134,
    name: "Blanche Jacobs",
    address: {
      country: "Croatia (Hrvatska)",
      city: "Norfolk",
      street_name: "Malbone Street",
      postal_code: "50-216",
      latitude: 50.8921,
      longitude: 16.1312,
      street_number: "48/8",
    },
    details: {
      courts_number: 4,
      hoops_number: 2,
      lightning: true,
    },
    created: "2015-12-22T12:25:14 -01:00",
  },
  {
    id: 62,
    name: "Gabriela Levine",
    address: {
      country: "Peru",
      city: "Maplewood",
      street_name: "Bassett Avenue",
      postal_code: "17-866",
      latitude: 51.8394,
      longitude: 16.5528,
      street_number: "54/19",
    },
    details: {
      courts_number: 4,
      hoops_number: 7,
      lightning: true,
    },
    created: "2015-07-01T01:55:53 -02:00",
  },
  {
    id: 249,
    name: "Britney Brock",
    address: {
      country: "Guatemala",
      city: "Sutton",
      street_name: "Harman Street",
      postal_code: "35-717",
      latitude: 51.2532,
      longitude: 17.0415,
      street_number: "31/10",
    },
    details: {
      courts_number: 2,
      hoops_number: 7,
      lightning: false,
    },
    created: "2019-04-22T11:26:05 -02:00",
  },
  {
    id: 230,
    name: "Baird Ware",
    address: {
      country: "Moldova",
      city: "Carlos",
      street_name: "Battery Avenue",
      postal_code: "28-703",
      latitude: 51.7879,
      longitude: 16.7602,
      street_number: "15/4",
    },
    details: {
      courts_number: 4,
      hoops_number: 3,
      lightning: true,
    },
    created: "2016-05-06T12:58:26 -02:00",
  },
  {
    id: 851,
    name: "Bean Smith",
    address: {
      country: "Puerto Rico",
      city: "Oasis",
      street_name: "Ridgecrest Terrace",
      postal_code: "39-783",
      latitude: 51.2916,
      longitude: 16.0954,
      street_number: "50/1",
    },
    details: {
      courts_number: 2,
      hoops_number: 2,
      lightning: false,
    },
    created: "2017-08-28T04:33:18 -02:00",
  },
  {
    id: 852,
    name: "Mcpherson Burch",
    address: {
      country: "Grenada",
      city: "Tonopah",
      street_name: "Meserole Avenue",
      postal_code: "67-787",
      latitude: 51.7493,
      longitude: 17.2832,
      street_number: "35/8",
    },
    details: {
      courts_number: 3,
      hoops_number: 2,
      lightning: false,
    },
    created: "2018-11-02T08:35:54 -01:00",
  },
  {
    id: 828,
    name: "Hancock Sanchez",
    address: {
      country: "Virgin Islands (British)",
      city: "Caln",
      street_name: "Amber Street",
      postal_code: "91-203",
      latitude: 51.7963,
      longitude: 17.9763,
      street_number: "59/14",
    },
    details: {
      courts_number: 1,
      hoops_number: 5,
      lightning: false,
    },
    created: "2016-03-29T10:55:48 -02:00",
  },
  {
    id: 361,
    name: "Tameka Sheppard",
    address: {
      country: "Botswana",
      city: "Darbydale",
      street_name: "Homecrest Avenue",
      postal_code: "60-194",
      latitude: 50.7729,
      longitude: 16.9067,
      street_number: "26/2",
    },
    details: {
      courts_number: 2,
      hoops_number: 4,
      lightning: false,
    },
    created: "2016-11-09T01:10:12 -01:00",
  },
  {
    id: 939,
    name: "Olive Hickman",
    address: {
      country: "Algeria",
      city: "Richville",
      street_name: "Hazel Court",
      postal_code: "22-975",
      latitude: 50.8296,
      longitude: 16.2111,
      street_number: "34/10",
    },
    details: {
      courts_number: 4,
      hoops_number: 8,
      lightning: false,
    },
    created: "2016-09-02T06:37:38 -02:00",
  },
  {
    id: 352,
    name: "Delacruz Grimes",
    address: {
      country: "New Caledonia",
      city: "Fairview",
      street_name: "Rugby Road",
      postal_code: "20-383",
      latitude: 50.5436,
      longitude: 16.73,
      street_number: "57/16",
    },
    details: {
      courts_number: 1,
      hoops_number: 5,
      lightning: false,
    },
    created: "2018-01-29T06:28:58 -01:00",
  },
  {
    id: 123,
    name: "Kristi Everett",
    address: {
      country: "Marshall Islands",
      city: "Baden",
      street_name: "Lincoln Terrace",
      postal_code: "97-366",
      latitude: 51.1155,
      longitude: 16.8577,
      street_number: "46/18",
    },
    details: {
      courts_number: 1,
      hoops_number: 4,
      lightning: true,
    },
    created: "2019-11-06T02:41:36 -01:00",
  },
  {
    id: 410,
    name: "Hartman Larsen",
    address: {
      country: "Chad",
      city: "Wilmington",
      street_name: "Bayview Avenue",
      postal_code: "47-579",
      latitude: 51.3755,
      longitude: 16.8495,
      street_number: "36/18",
    },
    details: {
      courts_number: 4,
      hoops_number: 6,
      lightning: false,
    },
    created: "2017-08-25T01:58:13 -02:00",
  },
  {
    id: 770,
    name: "Brianna Maldonado",
    address: {
      country: "Uzbekistan",
      city: "Sterling",
      street_name: "Bridgewater Street",
      postal_code: "15-527",
      latitude: 50.6191,
      longitude: 17.5694,
      street_number: "48/14",
    },
    details: {
      courts_number: 1,
      hoops_number: 8,
      lightning: false,
    },
    created: "2014-10-19T04:23:36 -02:00",
  },
  {
    id: 229,
    name: "Dollie Hensley",
    address: {
      country: "Bahrain",
      city: "Retsof",
      street_name: "Fuller Place",
      postal_code: "87-517",
      latitude: 51.3344,
      longitude: 16.9465,
      street_number: "16/5",
    },
    details: {
      courts_number: 4,
      hoops_number: 7,
      lightning: false,
    },
    created: "2020-10-11T04:21:46 -02:00",
  },
  {
    id: 135,
    name: "Tasha Hodge",
    address: {
      country: "Malawi",
      city: "Epworth",
      street_name: "Cobek Court",
      postal_code: "20-292",
      latitude: 51.9953,
      longitude: 16.2307,
      street_number: "38/2",
    },
    details: {
      courts_number: 2,
      hoops_number: 4,
      lightning: false,
    },
    created: "2021-03-08T08:42:42 -01:00",
  },
  {
    id: 170,
    name: "Briggs Rose",
    address: {
      country: "Norfolk Island",
      city: "Irwin",
      street_name: "Church Avenue",
      postal_code: "14-163",
      latitude: 50.9319,
      longitude: 16.733,
      street_number: "25/5",
    },
    details: {
      courts_number: 3,
      hoops_number: 2,
      lightning: false,
    },
    created: "2015-12-04T03:00:56 -01:00",
  },
  {
    id: 255,
    name: "Woods Buck",
    address: {
      country: "Ghana",
      city: "Walland",
      street_name: "Bijou Avenue",
      postal_code: "27-772",
      latitude: 51.04,
      longitude: 16.1188,
      street_number: "35/4",
    },
    details: {
      courts_number: 2,
      hoops_number: 8,
      lightning: false,
    },
    created: "2015-04-08T01:21:04 -02:00",
  },
];

export const sampleCourts2 = [
  {
    id: 1,
    name: "xd",
    address: {
      country: "Poland",
      city: "Wroclaw",
      street_name: "Zielinskiego",
      postal_code: "53-533",
      latitude: 56.0,
      longitude: 17.0,
      street_number: "49/2",
    },
    details: {
      courts_number: 2,
      hoops_number: 4,
      lightning: false,
      surface: "Dirt",
    },
    created: "2022-08-30T18:33:30.638235Z",
  },
  {
    id: 2,
    name: "test",
    address: {
      country: "Poland",
      city: "Dalachów",
      street_name: "Gabryśka",
      postal_code: "46-325",
      latitude: 53.0,
      longitude: 14.0,
      street_number: "12",
    },
    details: {
      courts_number: 1,
      hoops_number: 1,
      lightning: true,
      surface: "Rubber",
    },
    created: "2022-09-08T20:27:26.372975Z",
  },
];
